### ISSUE TITLE
pip3 install -r requirements.txtが実行できません

### ISSUE THREAD

**Issue by osuro33** [dsbook/dsbook#10]
requirements.txtがインストールされず、そのあとのpython3 generative_system.py -model dlg_model_step_100000.pt -replace_unk -src Noneが実行できません。
pip3 install -r requirements.txtを実行すると以下の文が赤文字ででてきます。
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-2g6uvwdj-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0evnj8xf-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-2g6uvwdj-build/

**Comment by osuro33** [comment]
こちらがpip3 install -r requirements.txtを実行したときの表示です。
/dsbook/OpenNMT-py$ pip3 install -r requirements.txt
Collecting git+https://github.com/pytorch/text.git@master#wheel=torchtext (from -r requirements.txt (line 4))
  Cloning https://github.com/pytorch/text.git (to master) to /tmp/pip-2g6uvwdj-build
Collecting six (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting tqdm==4.30.* (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/76/4c/103a4d3415dafc1ddfe6a6624333971756e2d3dd8c6dc0f520152855f040/tqdm-4.30.0-py2.py3-none-any.whl
Collecting torch>=1.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/38/53/914885a93a44b96c0dd1c36f36ff10afe341f091230aad68f7228d61db1e/torch-1.6.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting future (from -r requirements.txt (line 5))
Collecting configargparse (from -r requirements.txt (line 6))
Collecting requests (from torchtext==0.8.0a0+7905f0e->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl
Collecting numpy (from torchtext==0.8.0a0+7905f0e->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/22/e7/4b2bdddb99f5f631d8c1de259897c2b7d65dcfcc1e0a6fd17a7f62923500/numpy-1.19.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting sentencepiece (from torchtext==0.8.0a0+7905f0e->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/68/e5/0366f50a00db181f4b7f3bdc408fc7c4177657f5bf45cb799b79fb4ce15c/sentencepiece-0.1.92-cp36-cp36m-manylinux1_x86_64.whl
Collecting chardet<4,>=3.0.2 (from requests->torchtext==0.8.0a0+7905f0e->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->torchtext==0.8.0a0+7905f0e->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests->torchtext==0.8.0a0+7905f0e->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->torchtext==0.8.0a0+7905f0e->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Installing collected packages: six, tqdm, numpy, future, torch, configargparse, chardet, urllib3, idna, certifi, requests, sentencepiece, torchtext
  Running setup.py install for torchtext ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-2g6uvwdj-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0evnj8xf-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    -- Building version 0.8.0a0+7905f0e
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/torchtext
    copying torchtext/__init__.py -> build/lib.linux-x86_64-3.6/torchtext
    copying torchtext/utils.py -> build/lib.linux-x86_64-3.6/torchtext
    copying torchtext/version.py -> build/lib.linux-x86_64-3.6/torchtext
    copying torchtext/vocab.py -> build/lib.linux-x86_64-3.6/torchtext
    creating build/lib.linux-x86_64-3.6/torchtext/data
    copying torchtext/data/__init__.py -> build/lib.linux-x86_64-3.6/torchtext/data
    copying torchtext/data/batch.py -> build/lib.linux-x86_64-3.6/torchtext/data
    copying torchtext/data/dataset.py -> build/lib.linux-x86_64-3.6/torchtext/data
    copying torchtext/data/example.py -> build/lib.linux-x86_64-3.6/torchtext/data
    copying torchtext/data/field.py -> build/lib.linux-x86_64-3.6/torchtext/data
    copying torchtext/data/functional.py -> build/lib.linux-x86_64-3.6/torchtext/data
    copying torchtext/data/iterator.py -> build/lib.linux-x86_64-3.6/torchtext/data
    copying torchtext/data/metrics.py -> build/lib.linux-x86_64-3.6/torchtext/data
    copying torchtext/data/pipeline.py -> build/lib.linux-x86_64-3.6/torchtext/data
    copying torchtext/data/utils.py -> build/lib.linux-x86_64-3.6/torchtext/data
    creating build/lib.linux-x86_64-3.6/torchtext/datasets
    copying torchtext/datasets/__init__.py -> build/lib.linux-x86_64-3.6/torchtext/datasets
    copying torchtext/datasets/babi.py -> build/lib.linux-x86_64-3.6/torchtext/datasets
    copying torchtext/datasets/imdb.py -> build/lib.linux-x86_64-3.6/torchtext/datasets
    copying torchtext/datasets/language_modeling.py -> build/lib.linux-x86_64-3.6/torchtext/datasets
    copying torchtext/datasets/nli.py -> build/lib.linux-x86_64-3.6/torchtext/datasets
    copying torchtext/datasets/sequence_tagging.py -> build/lib.linux-x86_64-3.6/torchtext/datasets
    copying torchtext/datasets/sst.py -> build/lib.linux-x86_64-3.6/torchtext/datasets
    copying torchtext/datasets/text_classification.py -> build/lib.linux-x86_64-3.6/torchtext/datasets
    copying torchtext/datasets/translation.py -> build/lib.linux-x86_64-3.6/torchtext/datasets
    copying torchtext/datasets/trec.py -> build/lib.linux-x86_64-3.6/torchtext/datasets
    copying torchtext/datasets/unsupervised_learning.py -> build/lib.linux-x86_64-3.6/torchtext/datasets
    creating build/lib.linux-x86_64-3.6/torchtext/experimental
    copying torchtext/experimental/__init__.py -> build/lib.linux-x86_64-3.6/torchtext/experimental
    copying torchtext/experimental/functional.py -> build/lib.linux-x86_64-3.6/torchtext/experimental
    copying torchtext/experimental/transforms.py -> build/lib.linux-x86_64-3.6/torchtext/experimental
    copying torchtext/experimental/vectors.py -> build/lib.linux-x86_64-3.6/torchtext/experimental
    copying torchtext/experimental/vocab.py -> build/lib.linux-x86_64-3.6/torchtext/experimental
    creating build/lib.linux-x86_64-3.6/torchtext/nn
    copying torchtext/nn/__init__.py -> build/lib.linux-x86_64-3.6/torchtext/nn
    creating build/lib.linux-x86_64-3.6/torchtext/experimental/datasets
    copying torchtext/experimental/datasets/__init__.py -> build/lib.linux-x86_64-3.6/torchtext/experimental/datasets
    copying torchtext/experimental/datasets/language_modeling.py -> build/lib.linux-x86_64-3.6/torchtext/experimental/datasets
    copying torchtext/experimental/datasets/question_answer.py -> build/lib.linux-x86_64-3.6/torchtext/experimental/datasets
    copying torchtext/experimental/datasets/sequence_tagging.py -> build/lib.linux-x86_64-3.6/torchtext/experimental/datasets
    copying torchtext/experimental/datasets/text_classification.py -> build/lib.linux-x86_64-3.6/torchtext/experimental/datasets
    copying torchtext/experimental/datasets/translation.py -> build/lib.linux-x86_64-3.6/torchtext/experimental/datasets
    creating build/lib.linux-x86_64-3.6/torchtext/experimental/datasets/raw
    copying torchtext/experimental/datasets/raw/__init__.py -> build/lib.linux-x86_64-3.6/torchtext/experimental/datasets/raw
    copying torchtext/experimental/datasets/raw/language_modeling.py -> build/lib.linux-x86_64-3.6/torchtext/experimental/datasets/raw
    copying torchtext/experimental/datasets/raw/question_answer.py -> build/lib.linux-x86_64-3.6/torchtext/experimental/datasets/raw
    copying torchtext/experimental/datasets/raw/sequence_tagging.py -> build/lib.linux-x86_64-3.6/torchtext/experimental/datasets/raw
    copying torchtext/experimental/datasets/raw/text_classification.py -> build/lib.linux-x86_64-3.6/torchtext/experimental/datasets/raw
    copying torchtext/experimental/datasets/raw/translation.py -> build/lib.linux-x86_64-3.6/torchtext/experimental/datasets/raw
    creating build/lib.linux-x86_64-3.6/torchtext/nn/modules
    copying torchtext/nn/modules/__init__.py -> build/lib.linux-x86_64-3.6/torchtext/nn/modules
    copying torchtext/nn/modules/multiheadattention.py -> build/lib.linux-x86_64-3.6/torchtext/nn/modules
    running build_ext
    /home/osuro/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py:335: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    error: [Errno 2] No such file or directory: 'cmake': 'cmake'

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-2g6uvwdj-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0evnj8xf-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-2g6uvwdj-build/

**Comment by 1never** [comment]
torchtextがインストールできなくなっているようですので，別途pipでインストールします．

まず，OpenNMT-pyフォルダ内にあるrequirements.txtをエディタで開き，4行目の
git+https://github.com/pytorch/text.git@master#wheel=torchtext
を
#git+https://github.com/pytorch/text.git@master#wheel=torchtext
に変更して(先頭に#を付加する)保存してください．

次に，コンソール上で以下を実行してください．
$pip3 install -r requirements.txt
$pip3 install torchtext==0.4.0
$sudo python3 setup.py install

その後， generative_system.pyを実行してみてください．

**Comment by osuro33** [comment]
pip3 install torchtext == 0.4.0を実行すると以下の様に表示されます。generative_system.pyも実行できません。

pip3 install torchtext == 0.4.0
Invalid requirement: '=='
Traceback (most recent call last):
  File "/usr/share/python-wheels/packaging-17.1-py2.py3-none-any.whl/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1632, in parseString
    raise exc
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 3378, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 2689, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/usr/share/python-wheels/packaging-17.1-py2.py3-none-any.whl/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'=='"

**Comment by 1never** [comment]
==の前後のスペースが不要です．

**Comment by osuro33** [comment]
generative_system.pyは実行できましたが、返答がなく以下のような表示がでました。

python3 generative_system.py -model dlg_model_step_100000.pt -replace_unk -src None
/home/osuro/dsbook/telegram_bot.py:29: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
  updater = Updater(TOKEN)
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/osuro/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/osuro/.local/lib/python3.6/site-packages/telegram/ext/handler.py", line 122, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/osuro/dsbook/telegram_bot.py", line 23, in message
    system_output = self.system.reply(input)
  File "generative_system.py", line 34, in reply
    attn_debug=False
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-0.9.2-py3.6.egg/onmt/translate/translator.py", line 351, in translate
    batch, data.src_vocabs, attn_debug
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-0.9.2-py3.6.egg/onmt/translate/translator.py", line 544, in translate_batch
    return_attention=attn_debug or self.replace_unk)
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-0.9.2-py3.6.egg/onmt/translate/translator.py", line 695, in _translate_batch
    beam.advance(log_probs, attn)
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-0.9.2-py3.6.egg/onmt/translate/beam_search.py", line 164, in advance
    torch.div(self.topk_ids, vocab_size, out=self._batch_index)
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

**Comment by 1never** [comment]
$pip3 list 
でtorchのバージョンが1.2.0+cpuになっていますでしょうか．確認をお願いします．
なっていない場合はPyTorchの再インストールをしてください．

**Comment by osuro33** [comment]
無事解決しました。ありがとうございます！
