### ISSUE TITLE
Google Colaboratory上でのOpenNMT-pyのファイルを実行できません

### ISSUE THREAD

**Issue by ishidama2121** [dsbook/dsbook#18]
他の方のissuesにもありましたが、Google Colaboratory上で OpenNMT-py/preprocess.py OpenNMT-py/train.py OpenNMT-py/translate.pyの実行ができません。
同じく、エラー文も何も出ず実行が完了します。
Google Colaboratoryを再起動してみても実行できませんでした。
ランタイムのタイプ(GPU)も確認しました。

お手数をおかけしますが、ご確認よろしくお願いいたします。

**Comment by ikuhiroo** [comment]
同様のエラーに遭遇しました。

（いらないモジュールも入りますが）以下で、とりあえず対応できました。
```
!git clone https://github.com/OpenNMT/OpenNMT-py.git -b 0.9.2
!pip install OpenNMT-py==1.0.0rc1  # <- ここを追加
```

**Comment by ishidama2121** [comment]
無事実行できました！
誠にありがとうございます。
