### ISSUE TITLE
Mismatch attribute and value.

### ISSUE THREAD

**Issue by sca-shota-sato** [dsbook/dsbook#2]
p.61 図 2.7 
| 属性 | 値 |
|:---|:---:|
|place |大阪 |
|date |天気 |

とありますが、 `date` -> `type` ではないでしょうか。

**Comment by ryuichiro-higashinaka** [comment]
ご指摘ありがとうございます．確かにその通りです．次版で修正したいと思います．

**Comment by ryuichiro-higashinaka** [comment]
クローズします．
