### ISSUE TITLE
"Pythonでつくる対話システム"で使用されているニューラルネットワークについて

### ISSUE THREAD

**Issue by c1718035** [dsbook/dsbook#21]
お忙しい中大変申し訳ございません。
"Pythonでつくる対話システム"をご購入させて頂き
読破し終わった者ですが、ニューラルネットワーク（以下 : NN）についての
記述がほとんど無かったので質問させて頂いた次第です。

本書で使用されているニューラルネットワークは、
5層で宜しかったでしょうか？

以下のサイトを見てPyTorchでのNNが5層なのは理解しましたが、
本当にそうなのか半信半疑の状態が続いたので質問させて頂きました。
https://qiita.com/omiita/items/07e69aef6c156d23c538

また、ニューラルネットの色々な定義を決めているのは
"import torch.nn.functional as F"　が記載されている
"bert_evaluator.py"または、"dialogue_breakdown_detector.py"の
どちらかでしょうか？

functional.pyのソースを見ましたが、その中にある関数を
"import torch.nn.functional as F"　が記載されている２つソースで
関数を継承してる風には見受けられなかったので質問させて頂きました。

プログラムの理解力が不十分で大変申し訳ございません。

**Comment by 1never** [comment]
BERTのモデルの定義はTransformersライブラリにあります．
bert_evaluator.pyの場合，使用しているのは以下のBertForSequenceClassificationクラスになります．
https://github.com/huggingface/transformers/blob/master/src/transformers/models/bert/modeling_bert.py

層数似関してですが，本書ではBERTの学習済みモデルとしてGoogleが公開しているbert-base-multilingual-casedを使っています．
モデルの説明は以下にあります．
https://github.com/google-research/bert/blob/master/multilingual.md
この中に
>BERT-Base, Multilingual Cased (New, recommended): 104 languages, 12-layer, 768-hidden, 12-heads, 110M parameters
とありますので，層数としては12層です．

**Comment by c1718035** [comment]
大変お手数おかけしました、ご丁寧な解説ありがとうございました。
