### ISSUE TITLE
P210のコマンドでエラーが出てしまいます。

### ISSUE THREAD

**Issue by oidenomosa** [dsbook/dsbook#27]
P210のコマンド
　 pip3 install pyOpenSSL --no-cache-dir -I　を実行すると、
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask-ask 0.9.7 requires pyOpenSSL==17.0.0, but you have pyopenssl 20.0.1 which is incompatible.
flask-ask 0.9.7 requires six==1.10.0, but you have six 1.15.0 which is incompatible.
このようなエラーが出てしまいます。どうすればよいでしょうか、教えていただけると嬉しいです。

**Comment by masahiro-mi** [comment]
pipのアップデートによって、依存関係を解決するリゾルバが変わり、pyOpenSSLのインストールが失敗しているようです。

P210のコマンドは、Pythonインストール直後に行うので依存関係を解決するようなライブラリは入っていないと思いますが、
flask-askの要求が満たされていないと表示されているので、既に構築された環境での試行でしょうか？
以下のやり方のどちらかで、再度インストールを試していただけますでしょうか
1.  pip3 install pyOpenSSL --no-cache-dir -I --use-deprecated=legacy-resolver を実行して、今の環境にpyOpenSSLを導入する
2. 新しいPython環境を作成し、pip3 install pyOpenSSL --no-cache-dir -I -を実行する
