### ISSUE TITLE
generative_system.pyのscoresについて

### ISSUE THREAD

**Issue by Kate47** [dsbook/dsbook#29]
エラーが発生した等ではなく、質問となります。場所が異なっていたら申し訳ありません。
generative_system.pyの29行目にあるscoresは具体的にどのようなスコアなのでしょうか。
OpenNMT-pyのソースコードを確認してもよく理解できず、検索しても結果が出てきませんでした。
勉強不足の質問で申し訳ありませんが、よろしくお願いします。

**Comment by 1never** [comment]
簡単に言うと「文の長さで正規化した文の生成確率の対数をとった値」を意味します．

これを詳しく説明するためにはニューラルネットワークを用いた文章生成モデルについて理解する必要があります．
もし詳細を知りたい場合は「ゼロから作るDeep Learning ❷　自然言語処理編」の第7章を読むことをおすすめします．
https://www.oreilly.co.jp/books/9784873118369/
