### ISSUE TITLE
pip3 install python-telegram-bot==12.8実行時のエラーについて

### ISSUE THREAD

**Issue by zerohaji** [dsbook/dsbook#30]
P27のtelegramでの対話ができなかった為、python-telegram-botをバージョン指定でインストールしようとしたところ、 ModuleNotFoundError: No module named 'setuptools_rust'というエラーが発生し、実行完了しませんでした。以下がその時のログです。

zerohaji@DESKTOP-KE93AJP:~$ pip3 install python-telegram-bot==12.8
Collecting python-telegram-bot==12.8
  Downloading https://files.pythonhosted.org/packages/a6/2d/c72fc9a28144277f6170f2fcbfd3bd9427943497522b2689846596eb86cf/python_telegram_bot-12.8-py2.py3-none-any.whl (375kB)
    100% |████████████████████████████████| 378kB 2.2MB/s
Collecting tornado>=5.1 (from python-telegram-bot==12.8)
  Downloading https://files.pythonhosted.org/packages/01/d1/8750ad20cbcefb499bb8b405e243f83c2c89f78d139e6f8c8d800640f554/tornado-6.1-cp36-cp36m-manylinux1_x86_64.whl (427kB)
    100% |████████████████████████████████| 430kB 3.5MB/s
Collecting certifi (from python-telegram-bot==12.8)
  Downloading https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl (147kB)
    100% |████████████████████████████████| 153kB 7.1MB/s
Collecting decorator>=4.4.0 (from python-telegram-bot==12.8)
  Downloading https://files.pythonhosted.org/packages/bc/b4/c208a551033a7abb67703be73dea3d917dbce528bd87bcd6f7dfceec7097/decorator-5.0.7-py3-none-any.whl
Collecting cryptography (from python-telegram-bot==12.8)
  Downloading https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz (546kB)
    100% |████████████████████████████████| 552kB 3.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rb6rsgvb/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rb6rsgvb/cryptography/

以上

私はプログラミングの初心者で対話システムに興味があり、この本のを購入しました。
わからないなりに最後まで読んでP165までは実行してみました（telegram関連以外）。
環境 windows10 WSL Ubuntu18.04 

別のPCで最初から試してみたのですが、やはりこのpip3 install python-telegram-bot==12.8で
エラーが発生しました。pipのアップグレードというメッセージがあるようですがいろいろネットで検索しても意味がわかりませんでした。

様々なもののバージョンが当初と変わってしまい、私のような初心者にはtelegram環境での
テストが難しそうでしょうか？（だからコンソール環境のものが追記されているのでしょうか？）

この本が出版されてから１年以上が経過し、ほかの質問にも回答がされていない状況のようですが、すがる思いでgithubのアカウント登録をしてみました。

githubの利用ルールなども知らず、失礼があるかもしれません。
どうぞよろしくお願い致します。

**Comment by ryuichiro-higashinaka** [comment]
pip3 install --upgrade pip

でpip自体をアップデートしてから再度
pip3 install python-telegram-bot==12.8
を実行してみてはいかがでしょうか．

**Comment by zerohaji** [comment]
早速アドバイス下さりありがとうございます。
試してみましたら、pipのアップグレードも正常に実行され、python-telegram-bot==12.8も何かワーニングメッセージは出ましたがエラーは発生せず終了しました。

以下ログ
zerohaji@DESKTOP-KE93AJP:~$ pip3 install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 1.2MB/s
Installing collected packages: pip
Successfully installed pip-21.0.1
zerohaji@DESKTOP-KE93AJP:~$ pip3 install python-telegram-bot==12.8
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting python-telegram-bot==12.8
  Using cached python_telegram_bot-12.8-py2.py3-none-any.whl (375 kB)
Collecting tornado>=5.1
  Downloading tornado-6.1-cp36-cp36m-manylinux2010_x86_64.whl (427 kB)
     |████████████████████████████████| 427 kB 6.8 MB/s
Collecting decorator>=4.4.0
  Using cached decorator-5.0.7-py3-none-any.whl (8.8 kB)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from python-telegram-bot==12.8) (2.1.4)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from python-telegram-bot==12.8) (2018.1.18)
Installing collected packages: tornado, decorator, python-telegram-bot
Successfully installed decorator-5.0.7 python-telegram-bot-12.8 tornado-6.1

ありがとうございました！
早速telegramの対話など続きを試してみます。

＊このコメントをクローズするのは私なのでしょうか。
　とりあえず、先に実行結果の報告とお礼をお伝えしたかったので
　コメントボタンをクリックします。

**Comment by ryuichiro-higashinaka** [comment]
解決しましたので，クローズします．
