### ISSUE TITLE
Elasticsearchにアクセスできません

### ISSUE THREAD

**Issue by stchan130** [dsbook/dsbook#40]
第1版を購入しました
P135Elasticsearch の確認
『curl localhost:9200』 を実行すると
『curl: (52) Empty reply from server』となります。

Elasticsearchは『received plaintext http traffic on an https channel, closing connection Netty4HttpChannel』と表示されています

Elasticsearchは8.2.2をインストールしました

ご教示よろしくお願いいたします。

**Comment by masahiro-mi** [comment]
本書籍で利用するElasticsearchのバージョンは7.5.1になります。
P134~135にインストール手順が書かれておりますので、そちらを参照して再度インストールしてみてください。

**Comment by stchan130** [comment]
Elasticsearchのバージョンは7.5.1でアクセス出来ました
ありがとうございました。
