### ISSUE TITLE
Elasticsearchの接続ができない

### ISSUE THREAD

**Issue by brise-85** [dsbook/dsbook#42]
elasticsearchのインストールまではできたのですが，接続に関して下記の部分でエラーが出ます．
ご確認お願いします．
`>>> from elasticsearch import Elasticsearch`
`>>> es = Elasticsearch()`
`Traceback (most recent call last):`  
`File "<stdin>", line 1, in <module>`
  `File "/home/brise-85/anaconda3/envs/python36/lib/python3.6/site-packages/elasticsearch/_sync/client/__init__.py", line 191, in __init__`    
`raise ValueError("Either 'hosts' or 'cloud_id' must be specified")`
`ValueError: Either 'hosts' or 'cloud_id' must be specified`

**Comment by 1never** [comment]
pip3でインストールしたelasticsearchのバージョン指定ができているかを確認してください．
コマンドは以下のとおりです．
pip3 install elasticsearch==7.5.1

また，anacondaをお使いのようですが，anacondaは非推奨&動作未確認です．
書籍の通り，python3を使ってください．

**Comment by brise-85** [comment]
解決しました！
elasticsearchのバージョン指定が上手くできていなかったようです．
ありがとうございます．
