### ISSUE TITLE
3.4.4のgenerative_system.pyでエラーが発生する

### ISSUE THREAD

**Issue by akamiko1028** [dsbook/dsbook#44]
初心者で本書を参考にここまで問題なく進んでくることができたのですがどうしてもこの問題だけネット上を調べてみても解決に至らず、こちらで質問させていただければと思います。

問題箇所：
3.4.4:Google Colaboratoryによる学習
P.188（Kindleで拝読しているためページ数が異なる場合があります）
「インストールが完了したら、generative_system.pyを起動しましょう」
にて
`py .\generative_system.py -model .\dlg_model_step_100000.pt -replace_unk -src None`
を実行しましたが、
`AttributeError: 'Namespace' object has no attribute 'src_dir'`
と出て応答に応じません。
テレグラムのbotを動かした際の「こんにちは。対話を始めましょう。」は表示されています。

generative_system.pyの14行目に対して
`print(self.opt)`
を行うと、
`Namespace(align_debug=False, alpha=0.0, attn_debug=False, avg_raw_probs=False, ban_unk_token=False, batch_size=30, batch_type='sents', beam_size=5, beta=-0.0, block_ngram_repeat=0, config=None, coverage_penalty='none', data_type='text', dump_beam='', fp32=False, gpu=-1, ignore_when_blocking=[], int8=False, length_penalty='none', log_file='', log_file_level='0', max_length=100, max_sent_length=None, min_length=0, models=['.\\dlg_model_step_100000.pt'], n_best=1, output='pred.txt', phrase_table='', random_sampling_temp=1.0, random_sampling_topk=0, random_sampling_topp=0.0, ratio=-0.0, replace_unk=True, report_align=False, report_time=False, save_config=None, seed=-1, shard_size=10000, src='None', src_feats=None, stepwise_penalty=False, tgt=None, tgt_prefix=False, verbose=False)`
と確かにsrc_dirが存在しないことは確認できています。

これはどのように動かすのが正解なのでしょうか？

**Comment by akamiko1028** [comment]
環境ですが
Windows10
Python 3.7.4
 OpenNMT-py 2.2.0
 torch 1.12.1
 torchtext 0.5.0

です。

**Comment by akamiko1028** [comment]
#31 を参考にOpenNMT-pyの環境を作ったためここだけ書籍と異なっています。

**Comment by 1never** [comment]
トップページにも書かれていますが，第1刷からのアップデート情報を参照してください．
https://github.com/dsbook/dsbook/blob/master/eratta-taiwasystem_20220427.pdf
( #31 の投稿は2021年ですので，アップデート情報が出る前の情報です)

書かれているPyTorch，OpenNMTのバージョンが想定しているものと異なっていますので，まずは上記資料に従って環境構築を行ってください．

**Comment by akamiko1028** [comment]
環境を構築しなおしPDF通りのバージョンにしたことで
`src_dir=''`
が入るようになり無事動作しました。

ご回答いただきありがとうございました。
