### ISSUE TITLE
P134のElasticserchがインストールできない

### ISSUE THREAD

**Issue by osuro33** [dsbook/dsbook#7]
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: " to save to a file.
と出てダウンロードできません

**Comment by masahiro-mi** [comment]
状況の確認のために，実行したコマンド（curl -O https://~など）と，その実行結果（上記で書かれているWarningのログなどを含めて全体）を書いていただけますでしょうか．

よろしくお願いいたします．

**Comment by osuro33** [comment]
/dsbook $　curl -0 https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-linux-x86_64.tar.gz
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.

**Comment by masahiro-mi** [comment]
curlのオプションには-0（ゼロ）ではなく-O（アルファベットのオー）をご利用ください．
```
dsbook $　curl -O https://artifacts.elastic...
```

また，上記のコマンドをお試しいただいて，動いた場合でも，動かなかった場合でも，
再度ご連絡いただけますと幸いです．
（Issue #5 も同様ですが，動いた旨ご連絡いただけない場合，Issueを閉じることができないため，他の方から常にosuro33様のIssueが見える状態になってしまいます．）
よろしくお願いいたします．

**Comment by osuro33** [comment]
解決しました！
ありがとうございます。

**Comment by masahiro-mi** [comment]
解決したようで何よりです，本対応を持ってこのIssueを閉じさせていただきます．

引き続き， Issue #5の方でも，解決しましたらご連絡いただけますと幸いです．
よろしくお願いいたします．
